### PR TITLE
droute/matcher-domain: add gzip support

### PR DESCRIPTION
**Pull request by honwen**

### CODE REVIEW

**Comment by honwen** [comment]
first time use rust, code review needed

**Comment by LEXUGE** [comment]
Also, I am not sure if gz support is necessary, because even it seems like no one is releasing domain lists through gzip format. And in-memory decompressing still puts pressure on embedded machines like router.

**Comment by honwen** [comment]
> Also, I am not sure if gz support is necessary, because even it seems like no one is releasing domain lists through gzip format.

Agree, it a feature for own use, https://github.com/honwen/openwrt-dnsmasq-extra/tree/master/dnsmasq-extra/files/data
Or I maintain this feature in my own branch

> And in-memory decompressing still puts pressure on embedded machines like router.

need help for improving, refer: https://docs.rs/flate2/1.0.20/flate2/#async-io

**Comment by LEXUGE** [comment]
I have supported it with the latest commit. Instead of `gzip`, you can write directly `file: a.gz`

**Comment by honwen** [comment]
TKs for Ur patient

**Pull request closed without merging**
